# Generated by Django 5.0.2 on 2024-02-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge0_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='inputs',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='outputs',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
