# Generated by Django 5.0.2 on 2024-02-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge0_api', '0002_codesubmission_inputs_codesubmission_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='expected',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
